version: "3"

services: 

  server: 
    container_name: "server"
    build: .
    command: npm run dev
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules

    ports: 
      - 4000:4000
    restart: always
    links: 
      - database
    environment:
      PORT: 4000
      PATH_GRAPHQL: "/graphql"
      MONGO_URI: database
      MONGO_PORT: 27017
      MONGO_DB: "cryptome"
      KEY: "8hgkgvrdrQ"
  
  database:
    container_name: "database"
    image: mongo
    volumes: 
      - ./data:/data/db
    ports:
      - 27017:27017
